"""
Today, we will be explicitly enumerating the elements of the Weyl group of E6.

We will work in the following embedding inside of R^9:

One possible selection for the simple roots of E6 is:

(0,0,0;0,0,0;0,1,-1)
(0,0,0;0,0,0;1,-1,0)
(0,0,0;0,1,-1;0,0,0)
(0,0,0;1,-1,0;0,0,0)
(0,1,-1;0,0,0;0,0,0)
(1/3, -2/3, 1/3; -2/3, 1/3, 1/3, -2/3, 1/3, 1/3)

The Weyl group of E6 is generated by reflections in the
hyperplanes orthogonal to these roots.
"""

import numpy as np

SIMPLE = [
    np.array([0, 0, 0, 0, 0, 0, 0, 1, -1]),
    np.array([0, 0, 0, 0, 0, 0, 1, -1, 0]),
    np.array([0, 0, 0, 0, 1, -1, 0, 0, 0]),
    np.array([0, 0, 0, 1, -1, 0, 0, 0, 0]),
    np.array([0, 1, -1, 0, 0, 0, 0, 0, 0]),
    np.array([1/3, -2/3, 1/3, -2/3, 1/3, 1/3, -2/3, 1/3, 1/3])
]


SIMPLE_REFLECTIONS = [np.identity(
    9) - 2 * np.outer(s, s) / np.dot(s, s) for s in SIMPLE]

WEYL_GROUP = [np.identity(9)]
WEYL_EXPANSION = [()]

DISC = 2 ** 16

WEYL_GROUP_SET = set([tuple(int(i) for i in w.reshape(81) * DISC + 0.5)
                     for w in WEYL_GROUP])  # for fast membership testing

i = 0
while i < len(WEYL_GROUP):
    for j, s in enumerate(SIMPLE_REFLECTIONS):
        test = np.matmul(s, WEYL_GROUP[i])
        test_tuple = tuple(int(i) for i in test.reshape(81) * DISC + 0.5)
        if test_tuple not in WEYL_GROUP_SET:
            WEYL_GROUP.append(test)
            WEYL_GROUP_SET.add(test_tuple)
            WEYL_EXPANSION.append(WEYL_EXPANSION[i] + (j,))
    i += 1

print("The Weyl group of E6 has cardinality " + str(len(WEYL_GROUP)) + ".")

# Find the unique element of the Weyl group which sends
# The simple roots to some permutation of the inverses of the simple roots.

res = None

for n, w in enumerate(WEYL_GROUP):
    NEW_SIMPLE = [np.matmul(w, s) for s in SIMPLE]
    found_all = True
    for i in NEW_SIMPLE:
        found = False
        for j in SIMPLE:
            if np.allclose(i, -j):
                found = True
                break
        if not found:
            found_all = False
            break
    if found_all:
        res = n
        break

print("The unique element of the Weyl group which " +
      "sends the simple roots to their inverses is:")
print("1/3 * \n" + np.round(3 * WEYL_GROUP[res], 3).__str__())
print("This element can be expanded as:")
print(WEYL_EXPANSION[res])
# print("As matrices:")
# for i in WEYL_EXPANSION[res]:
#     print(SIMPLE_REFLECTIONS[i])

print("This permutes the roots as follows:")

permutation = []
for i in SIMPLE:
    for j, k in enumerate(SIMPLE):
        if np.allclose(i, -np.matmul(WEYL_GROUP[res], k)):
            permutation.append(j)
            break

print(permutation)
